### ISSUE TITLE
Failed to locate XSD resource '/META-INF/schema/edi-message-mapping-1.5.xsd'

### ISSUE THREAD

**Issue by rcyrus** [smooks/smooks#107]
I am trying to use the EJC features of this library however I am unable to run the examples (or my own code for that matter).

I get this error message:

`Failed to locate XSD resource '/META-INF/schema/edi-message-mapping-1.5.xsd' on classpath. Namespace: 'http://www.milyn.org/schema/edi-message-mapping-1.5.xsd'.`

It appears that milyn.org is parked. Is there another location I should be using?

**Comment by 1906048** [comment]
hello. im facing the same issue ..could you please explain how did you fix this
