### ISSUE TITLE
FreeMarker dependency outdated

### ISSUE THREAD

**Issue by ddekany** [smooks/smooks#123]
According to your parent `pom.xml` you are still using FreeMarker 2.3.21. The current stable release is `2.3.25-incubating`, so users miss out on some improvements/fixes. Perhaps the most relevant for Smooks is that instead of `.vars['foo-bar']`, `.vars['ns:foo']`, `parent['foo-bar']` etc., since 2.3.22 they could write `foo\-bar`, `ns\:foo`, `parent.foo\-bar` (which then should be used in the User Guide as well). See also: http://freemarker.org/docs/app_versions.html

**Comment by hicolour** [comment]
@ddekany pull request  with upgrade will be very welcome :pray:

**Comment by claudemamo** [comment]
This was addressed in PR https://github.com/smooks/smooks/pull/233.
