### ISSUE TITLE
java to edi

### ISSUE THREAD

**Issue by huangdan19880113** [smooks/smooks#124]
How can I generate an EDI file from java or xml ? I'm looking for  exzamples， thanks。

**Comment by hackmann** [comment]
For UN/edifact look at the dedicated sample repository
https://github.com/smooks/unedifact-examples

And some of smooks-examples also include edifact:

* edi-to-java
* edi-to-xml
* edi-with-import-to-java
* ejc

**Comment by ashutoshbaghel** [comment]
Is writing to EDI only possible using the UNEDIFACT classes? 
Is there a generic example like there is for edi-to-xml and edi-to-java within the smooks/smooks repository?

**Comment by claudemamo** [comment]
Closing since the original query was answered.
