### ISSUE TITLE
IATA PADIS Support

### ISSUE THREAD

**Issue by sureshbabukota** [smooks/smooks#125]
Hi, Whether SMooks supports IATA PADIS? If So can I directly import the structure?

Hi, I am evaluating Smooks for Flat file to EDI( IATA PADIS ) conversion. in the below link section 2.1 It was mentioned that by loading the SMOOKS jar file we can create of modify the Smooks config.xml through GUI. Even though I downloaded the jar file and added it I don't Smook category in New file creation.
https://devstudio.jboss.com/download/documentation/PDF/JBoss_Developer_Studio-3.0-Smooks_Developer_Tools_Reference_Guide-en-US.pdf

The jar FIle downloaded from below site.
https://jar-download.com/explore-java-source-code.php?a=milyn-smooks-all&g=org.milyn&v=1.7.0&downloadable=1

Please suggest,,

**Comment by hackmann** [comment]
Yes, smooks supports IATA PADIS. But you need to manually write an EDI mapping model for the messages you are interested in.

Please read the EDI section of the user guide
http://www.smooks.org/user-guide/user-guide.html#EDI
