### ISSUE TITLE
EDI parsing does not handle segment groups with an optional first segments

### ISSUE THREAD

**Issue by mtruchard** [smooks/smooks#126]
I have EDI x837 data that seems to make use of an optional first segment in the "drug identification 2410" loop. The group starts with an optional LIN segment followed by a CTP segment and can repeat 0 to 25 times. The spec I have says that the LIN segment is optional but I don't see a way to configure the smooks edi mapping to detect a segment group with an optional first segment for a repeated segment. I read up on EDI and 837 and it seems that this is valid. One doc said that a loop will repeat until segments are found that fall outside of the loop. Another doc said that *normally* a loop is detected when its first segment is hit again. I'm not 100% sure on the EDI rules around this.

Here is some example data:

LIN||N4|00703722102
CTP||||1|ML
LIN||N4|0338954206
CTP||||1|ML
CTP||||1|ME

And here is an extract from the config:

```
<medi:segmentGroup xmltag="DrugIdentification_2410" minOccurs="0" maxOccurs="25">
	<medi:segment segcode="LIN" xmltag="DrugIdentification" minOccurs="0" maxOccurs="1" truncatable="true">
		<medi:field xmltag="DrugAssignedIdentification" />
	</medi:segment>
	<medi:segment segcode="CTP" xmltag="DrugQuantity" minOccurs="0" maxOccurs="1" truncatable="true">
		<medi:field xmltag="DrugClassOfTradeCode" />
	</medi:segment>
</medi:segmentGroup>
```

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
