### ISSUE TITLE
EDI parser does not support fields with cardinality larger than 1

### ISSUE THREAD

**Issue by mtiitson** [smooks/smooks#127]
A specific case: 
COM segment in PAXLST message is defined to have 3 instances of field C076. 

Segment from example message:
`COM+555 123 456789:TE+555 123 456780:FX+HELPDESK AT FLYAIR.COM:EM'`

The mapping for the segment for example in d02b-mapping library is:
```xml
<medi:segment xmltag="COMMUNICATION_CONTACT" truncatable="true" segcode="COM" minOccurs="1" maxOccurs="1"
              ignoreUnmappedFields="false"
              description=" To identify a communication number of adepartment or a person to whom communicationshould be directed.">
<medi:field xmltag="COMMUNICATION_CONTACT" truncatable="true" required="true" nodeTypeRef="C076">
  <medi:component xmltag="Communication_address_identifier" truncatable="true" required="true" minLength="0"
                  maxLength="512" dataType="String">
  <medi:component xmltag="Communication_means_type_code" truncatable="true" required="true" minLength="0" maxLength="3"
                  dataType="String">
    <medi:documentation>Code specifying the type of communication address.</medi:documentation>
  </medi:component>
</medi:field>
</medi:segment>
```

Using the mapping to parse PAXLST message results in an exception:
`org.milyn.edisax.EDIParseException: EDI message processing failed [PAXLST][D:02B:UN].  Segment [COM] expected to contain 1 fields.  Actually contains 3 fields (not including segment code).  Currently at segment number 6`

Looking at the edi-message-mapping.1.4.xsd there doesn't seem to be any way to write a mapping to fields with cardinality larger than 1 other than to explicitly name each occurrence of the field in the segment. 

Please correct me if this is actually possible. And if so, is there a way to still make use of pre-built UN/EDIFACT mappings?

**Comment by hackmann** [comment]
You are right, the EDIMAP does not expose field repetition beside having a delimiter for it.

In you case if you change the message to use a field repeat delimiter like `*`
`COM+555 123 456789:TE*555 123 456780:FX*HELPDESK AT FLYAIR.COM:EM'`

It would parse the EDI and generate SAX events. Still no way to say only 3 are allowed but not 4. And the `EJC` part that generates java beans and bindings does not know about it either.

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
