### ISSUE TITLE
milyn.org is dead

### ISSUE THREAD

**Issue by taowu99** [smooks/smooks#128]
All the smooks-config.xml are referring the csv-*.xsd file on milyn.org.  Since milyn.org is not accessible anymore, the smooks fails

**Comment by claudemamo** [comment]
The XSDs are now hosted on https://www.smooks.org (e.g., https://www.smooks.org/xsd/smooks/csv-1.5.xsd). The docs were updated to reflect this and future releases will reference the new URLs.
