### ISSUE TITLE
SAX content handler that generates edifact messages

### ISSUE THREAD

**Issue by hackmann** [smooks/smooks#135]
In version 1.7.0 smooks can parse Edifact messages and based on an Edimap generate XML documents. But it cannot convert these XML document back to Edifact.

Either EJC must be used to generate java beans with embedded EDI writable implementation. Or a custom template for this specific message.

**Comment by claudemamo** [comment]
The _unparser_ resources in the overhauled EDI/EDIFACT cartridges support the requested feature.
