### ISSUE TITLE
SBT plugin for EJC

### ISSUE THREAD

**Issue by love2dishtech** [smooks/smooks#152]
Hi Team,

We do have the maven plugin for EJC(https://github.com/smooks/smooks/tree/master/edi/ejc/maven-ejc-plugin), in order to generate Java models given the smooks mapping xml file. Do we have a similar plugin for SBT for the Scala developers.

As there is no support for using maven plugins in SBT, it becomes tricky to generate models as part of the build process for Scala users.

Thanks

P.S: I will be happy to write one and submit a PR, if we don't have something planned.

**Comment by JeSuisAlrick** [comment]
@love2dishtech, it would probably be a good idea if you fork the repo and write the plugin. The maintainers of this repo hardly reply to messages.

**Comment by claudemamo** [comment]
The EDIFACT Java Compiler was removed in Smooks 2.  Now we generate the Java models using a common Maven XJC plugin. It should be easy to reproduce the process in SBT.

**Comment by mcmpp** [comment]
Hi @claudemamo ,

as you mention on this ticket, in version 2 you are not using edifact java compiler anymore. In the documentation, you only have this way for parsing edifact files https://www.smooks.org/documentation/index#ejc---edifact-java-compiler. Do you have any example or documentation on how I should parse edifact files in version 2?? 

thanks for your help

**Comment by claudemamo** [comment]
Missed your comment @mcmpp. Plenty of Smooks 2 examples are found in the [examples repo](https://github.com/smooks/smooks-examples). Take a look at the [EDI-to-Java](https://github.com/smooks/smooks-examples/tree/v1.0.2/edi-to-java) and [EDI-to-XML](https://github.com/smooks/smooks-examples/tree/v1.0.2/edi-to-xml) examples. Hope it helps!

**Comment by mcmpp** [comment]
Hi @claudemamo ,

no worries, I was able to make it work and now I am using it in my project. Thanks for your great  work!
