### ISSUE TITLE
Smooks is no longer active

### ISSUE THREAD

**Issue by sabiya** [smooks/smooks#160]
Hello,
I am unable to join user mailing list.
Recently, we used smooks in beta release to solve simple transformation problem for Java. Now, we are planning to use smooks as Transformation Engine in major release for other data types. 
But,we just got to know that its no longer under active project list.
So our team is now thinking whether to go with smooks or not.
Can you please share your views on this?
Any updates on if it will be maintained by JBoss community or under Apache community in upcoming time.

Regards,
Sabiya

**Comment by claudemamo** [comment]
The project is no longer dormant. Stay tuned for the next upcoming release.
