### ISSUE TITLE
EJC generates v1.5 edimap file from v1.6

### ISSUE THREAD

**Issue by ben-manes** [smooks/smooks#162]
I set up Smooks EJC through Gradle (via the Ant plugin) to generate from a 204 EDI mapping, where I have `segments` set with `ignoreUnmappedSegments="true"`. The generated output `edimappingconfig.xml` does not include this, probably because it writes using `edi-message-mapping-1.5.xsd` whereas the original has v1.6. Since I am learning and iterating on the EDI integration, I started by only mapping the first two lines. When only this subset, reading and writing work flawlessly.

If I end up wanting this, the workaround might be just to copy my original mapping file to the generated output directory using a `copy` task.

The Gradle work is pretty straightforward, so including in case that's helpful for someone else.

```gradle
configurations {
  ejc
}

dependencies {
  ejc "org.milyn:milyn-smooks-ejc:${versions.smooks}"
}

task generateEdi {
  doLast {
    ant.taskdef(
      name: 'EJCAntTask',
      classname: 'org.milyn.ejc.ant.EJCAntTask',
      classpath: configurations.ejc.asPath)
    ant.EJCAntTask(
      edimappingmodel: "${projectDir}/src/main/resources/edi/204.xml",
      destdir: "${buildDir}/generated-sources/edi",
      packagename: 'com.example.generated.edi')
  }
}

sourceSets.main.java.srcDirs += "${buildDir}/generated-sources/edi"
generateEdi.dependsOn(processResources)
compileJava.dependsOn(generateEdi)
```

**Comment by ben-manes** [comment]
This is really annoying because it doesn't bring in the property `ignoreUnmappedSegments`, causing parsing to fail of a fully defined EDI mapping. In xsd-1.6 this should be set, but it isn't. The `Factory` class then has it defaulted to `null`, which is interpreted as `false`. This has to be mucked with during the build to replace this file and have a correct resource.

```xml
<!-- input -->
<medi:segments xmltag="CarrierLoadTenderResponse" ignoreUnmappedSegments="true">

<!-- output -->
<medi:segments xmltag="CarrierLoadTenderResponse">
```

**Comment by ben-manes** [comment]
The following works well, where the source mapping is named `${code}.xml`, where code is the EDI identifier code (e.g. 204, 990). The remaining quirk is that cross-referencing mapping definitions don't seem to work, e.g. defining the X12 headers and referencing them in the mapping file. This is because the Ant task resolves the path against Gradle's internal directory (daemon's execution dir) rather than the project's. For now I duplicate but may investigate a fix later.

This version is more complex to bundle the EDI classes in their own jar, so that the lint warnings can be suppressed.

```gradle
import org.gradle.plugins.ide.eclipse.model.SourceFolder

apply plugin: 'idea'

configurations {
  ejc
}

sourceSets {
  ejc {
    java.srcDir "${buildDir}/generated-sources/edi"
    resources.srcDir "${buildDir}/generated-sources/edi"
  }
}

task ejcJar(type: Jar, dependsOn: ejcClasses) {
  baseName = "${baseName}-edi"
  from sourceSets.ejc.output
}

artifacts {
  ejc ejcJar
}

dependencies {
  ejcCompile smooksEjc
  compile project(path: project.path, configuration: 'ejc')
}

task generateEdi {
  inputs.dir file("${projectDir}/src/main/resources/edi")
  outputs.dir "${buildDir}/generated-sources/edi"

  doLast {
    ant.taskdef(
      name: 'EJCAntTask',
      classname: 'org.milyn.ejc.ant.EJCAntTask',
      classpath: configurations.ejcCompile.asPath)
    def directory = file("${projectDir}/src/main/resources/edi")
    for (def filename : directory.list()) {
      def code = filename.take(filename.lastIndexOf('.'))
      def destination = "${buildDir}/generated-sources/edi"
      def packageName = "com.example.generated.edi.edi${code}"
      def mapping = "${projectDir}/src/main/resources/edi/${filename}"
      def packageDir = "${destination}/${packageName.replace('.', '/')}"
      ant.EJCAntTask(
        edimappingmodel: mapping,
        packagename: packageName,
        destdir: destination)
      copy {
        from mapping
        into packageDir
        rename "${code}.xml", 'edimappingconfig.xml'
      }
    }
  }
}

compileEjcJava {
  dependsOn(generateEdi)
  options.compilerArgs += '-Xlint:none'
}

plugins.withType(EclipsePlugin) {
  project.eclipse.classpath.file.whenMerged {
    entries.findAll { it instanceof SourceFolder && it.output == 'bin/ejc' }*.output = 'bin/main'
  }
}

idea {
  module {
    sourceDirs += file("${buildDir}/generated-sources/edi")
    generatedSourceDirs += file("${buildDir}/generated-sources/edi")
  }
}
```

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
