### ISSUE TITLE
the attr of minOccurs became "realOccurs" in the EDI mapping

### ISSUE THREAD

**Issue by nonicknamelala** [smooks/smooks#255]
<medi:segmentGroup minOccurs="1" maxOccurs="-1" xmltag="tolb">
			<medi:segment segcode="LIN" xmltag="tolb-lin" maxOccurs="1" ignoreUnmappedFields="true">
				<medi:field xmltag="line-no" />
				<medi:field xmltag="lin2" />
				<medi:field xmltag="olitn" />
			</medi:segment>
			<medi:segment segcode="QTY" xmltag="tolb-qty" maxOccurs="1" ignoreUnmappedFields="true">
				<medi:field xmltag="qty" />
			</medi:segment>
		</medi:segmentGroup>

I'm testing edi-to-java with a customer order in the format of EANCOM, I set a group segment for the SKU lines in the mapping file such as above. there are 2 SKUs in the EDI, but it only mapped 1 SKU. then I changed minOccurs to "2" in medi:segmentGroup, then it mapped 2 SKUs. it seems the attr of minOccurs became "realOccurs".

**Comment by nonicknamelala** [comment]
after testing, I found if adding the last segment "PAC" in the segmentGroup of the mapping and set it's minOccurs="1"(it is necessary), then it works as expected, I ignored that segment before. But it brings another problem that, if all the segments after "QTY" is optional, how to solve that?

		<medi:segmentGroup maxOccurs="1000" minOccurs="1" xmltag="tolb">
			<medi:segment segcode="LIN" xmltag="tolb-lin" maxOccurs="1" minOccurs="1" ignoreUnmappedFields="true">
				<medi:field xmltag="line-no" />
				<medi:field xmltag="lin2" />
				<medi:field xmltag="olitn" />
			</medi:segment>
			<medi:segment segcode="QTY" xmltag="tolb-qty" maxOccurs="1" minOccurs="1" ignoreUnmappedFields="true">
				<medi:field xmltag="qty" />
			</medi:segment>
			<medi:segment segcode="PAC" xmltag="tolb-pac" maxOccurs="1" minOccurs="1" ignoreUnmappedFields="true" />
		</medi:segmentGroup>

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
