### ISSUE TITLE
DABigDecimalDecoder

### ISSUE THREAD

**Issue by jensb1** [smooks/smooks#29]
Hello, 

Would suggest that you use #0.# in the decimal encoding instead of #0.0# even if that is compliant to standards. Alot of implementation require no decimal and it has really no purpose of enforcing at least one decimal.

DIFF

diff --git a/smooks-cartridges/edi/src/main/java/org/milyn/javabean/decoders/DABigDecimalDecoder.java b/smooks-cartridges/edi/src/main/java/org/milyn/javabean/decoders/DABigDecimalDecoder.java
index 1f493cc..8831f69 100644
--- a/smooks-cartridges/edi/src/main/java/org/milyn/javabean/decoders/DABigDecimalDecoder.java
+++ b/smooks-cartridges/edi/src/main/java/org/milyn/javabean/decoders/DABigDecimalDecoder.java
@@ -82,7 +82,7 @@ public class DABigDecimalDecoder extends BigDecimalDecoder {
     private synchronized void setDecimalPointFormat(DecimalFormat decimalFormat, Delimiters interchangeDelimiters) {
         DecimalFormatSymbols dfs = decimalFormat.getDecimalFormatSymbols();
-        decimalFormat.applyPattern("#0.0#");
-        decimalFormat.applyPattern("#0.#");
       if (interchangeDelimiters != null) {
           dfs.setDecimalSeparator(interchangeDelimiters.getDecimalSeparator().charAt(0));
       }

**Comment by mkleijwegt** [comment]
Today I read an IFTMIN 95B message and directly wrote it. What I see is that the output differs from the input with regard to the decimals. For instance when I read GID+2+5' it is written as GID+2.0+5.0'. I suppose this issue has not been resolved? Is there any way to programmatically configure this?

**Comment by raviu** [comment]
I've run into a similar issue. Smooks EDIFACT output is always to two decimal places. 

Wouldn't hardcoding the value to a particular format make it too restrictive? What if a vendor requires a particular decimal format? Ideal solution would be to make this configurable.

**Comment by bnserig** [comment]
Hi,

I need 3 fraction digits but #0.0# is hardcoded in DABigDecimalDecoder. How can I do this ?

**Comment by szygie** [comment]
Hi
Hope this will help someone...

As I encounter similar issue where BigDecimal rounding takes place. Also LIN item number was present with decimal point...I came to idea to modify used classes for example:

public class LINLineItemSzygie extends LINLineItem implements Serializable, EDIWritable {

public LINLineItemSzygie(LINLineItem oldObject){
//contructor that make life easier ;)
}

...
//Overrided methods (escepecially write method) //refactor code to your needs, you can remove reference to DABigDecimalDecoder
...
}

On interchange message, object where you are calling write method, update it with new class. For exmple
{
var lin = el.getLINLineItem();
if (!(lin instanceof LINLineItemSzygie)) {
el.setLINLineItem(new LINLineItemSzygie(lin));
}

Now, when you call write on updated object, you should see output in your implementation.
