### ISSUE TITLE
smooks.org

### ISSUE THREAD

**Issue by NishankGandhi** [smooks/smooks#470]
Hi,
Seems like smooks.org has a lot of document about this framework which is down right now. Any plan to bring it up again or is it migrated to some other domain?

Regards,
Nishank

**Comment by claudemamo** [comment]
We're working on resolving it. In the meantime, you can find the latest
Smooks 2 docs here: https://github.com/smooks/smooks/blob/master/README.adoc

Claude

**Comment by NishankGandhi** [comment]
smooks.org is up now. Thank you!

Closing the issue.
