### ISSUE TITLE
error in opening zip file in Initialisation

### ISSUE THREAD

**Issue by paulsen-it** [smooks/smooks#480]
In this code:
`Smooks smooks = new Smooks("conf/smooks-config.xml");`
I get the error "`error in opening zip file`"

This comes from `org.smooks.classpath.Scanner.scanClasspath`.

The debug log shows that the Scanner want to unzip an *.pom textfile:
`DEBUG org.smooks.classpath.Scanner:57:handleArchive:118 ~ Scanning archive: C:\Users\User\.m2\repository\com\sun\xml\ws\jaxws-ri\2.3.0\jaxws-ri-2.3.0.pom`

This comes from my Maven projects dependencies:
```
<dependency>
	<groupId>com.sun.xml.ws</groupId>
	<artifactId>jaxws-ri</artifactId>
	<version>2.3.0</version>
	<type>pom</type>
</dependency>
```

Please filter pom-Files or ignoring this kind of error. I think it is better to ignore, because it is not relevant to start Smooks.
Error happens in M2 and M3.
A M3-Maven Repository for smooks-all doesn't exists.

**Comment by ShawnSWu** [comment]
I face the same issue, Have any solutions for this problem?

**Comment by claudemamo** [comment]
We'll try to resolve this by the next release.

**Comment by robbiebaske** [comment]
Hello. Any info why it was removed from RC2 ? I was monitoring this one closely for RC2 release. Because of this issue i am not able to build a connector with mule sdk containing smooks2

**Comment by claudemamo** [comment]
Frankly this fell off my radar and RC2 was released like a week ago. Will escalate its priority and tackle it for the next release.
