### ISSUE TITLE
Question: Smooks seems to scan all project dependencies - how do I prevent that?

### ISSUE THREAD

**Issue by domids** [smooks/smooks#486]
On intializing Smooks I get a lot of ClassNotFoundExceptions and NoClassDefFoundErrors. In addition, it takes nearly a minute to initalize Smooks and create a simple DESADV file.

The following libraries are used in the pom.xml:

    <properties>
        <smooks.version>2.0.0-M2</smooks.version>
    </properties>
    ...
        <dependency>
            <groupId>org.smooks.cartridges.edi</groupId>
            <artifactId>smooks-edifact-cartridge</artifactId>
            <version>${smooks.version}</version>
        </dependency>
        <dependency>
            <groupId>org.smooks.cartridges.edi</groupId>
            <artifactId>d01b-edifact-binding</artifactId>
            <version>${smooks.version}</version>
        </dependency>
        <dependency>
            <groupId>org.smooks.cartridges.edi</groupId>
            <artifactId>edifact-schemas</artifactId>
            <version>${smooks.version}</version>
            <classifier>d01b</classifier>
        </dependency>
        ...

Content of the smooks-config.xml:

```
<?xml version="1.0"?>
<smooks-resource-list xmlns="https://www.smooks.org/xsd/smooks-2.0.xsd"
                      xmlns:edifact="https://www.smooks.org/xsd/smooks/edifact-2.0.xsd">

    <edifact:unparser schemaURI="/d01b/EDIFACT-Messages.dfdl.xsd" unparseOnElement="/Interchange">
        <edifact:messageTypes>
            <edifact:messageType>DESADV</edifact:messageType>
        </edifact:messageTypes>
    </edifact:unparser>

</smooks-resource-list>
```

Smooks is intialized like this:
`Smooks smooks = new Smooks("smooks-config.xml");`
This takes nearly a minute to complete and a lot of ClassNotFoundExceptions are happening (see https://pastebin.com/ggPFtJBV for an excerpt).

I suspect it takes so long, because my project has a lot of dependencies and Smooks is scanning all of them - could this be the case?

**How do I initialize Smooks correctly so it doesn't scan all the project dependencies?**

**Comment by domids** [comment]
Thanks for the tip about `cacheOnDisk`- sadly it doesn't seem to improve initializiation time much in my project.

Here is a small sample project with a lot of dependencies. It just initializes Smooks, which takes about 14 seconds on my machine. In addition a lot ClassNotFoundExceptions are thrown.
https://github.com/domids/smooks-startup-test

Thank you very much for your effort!

**Comment by claudemamo** [comment]
Your application started up on my machine without a hitch on Java 11 but I do get errors for Java 8:

`java.lang.UnsupportedClassVersionError: META-INF/versions/11/module-info has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

My guess is that one or more app dependencies are Java 8 incompatible.

**Comment by domids** [comment]
@claudemamo That's interesting. I use AdoptOpenJDK 1.8.0_292 to start the application. There is no `UnsupportedClassVersionError`.
