### ISSUE TITLE
Memory issue with edi to java parsing | smooks version: 2.0.0-RC1

### ISSUE THREAD

**Issue by DimitrisMarm** [smooks/smooks#540]
Hello there, 

I have create a service that receive Edi message and parse/filter it to java models object. 
My issue is that when the service receives an Edi message it keeps it in the memory after the parsing and the processing is finished, which leads to "out of memory" exception.

Is there any way to clear the memory after the end of the message processing?

**Comment by claudemamo** [comment]
About this, you can implement `org.smooks.api.lifecycle.ExecutionLifecycleCleanable`. The `executeExecutionLifecycleCleanup` method is called at the end of a Smooks execution so you can perform the clean-up inside this method.
