### ISSUE TITLE
MILYN-658 - Groovy upgrade

### ISSUE THREAD

**Issue by hicolour** [smooks/smooks#57]
Generally everything works fine beside 3 tests .. ;)

The problem is that org.milyn.delivery.dom.DOMBuilder#characters is receives  splited  xml data and then double add last chars.

It's hard to explain how groovy affects because when I tested groovy code itself I got valid output.

I will try to solve it but maybe someone will have idea what's the root cause.

Notes in gist
https://gist.github.com/hicolour/801ecc7f14f124c2e7f6#file-smooks-xerces

++
when input data is shorter problem does not occur

**Comment by jcordes73** [comment]
@hicolour I have provided now a fix for Groovy 2.3.9. Can you have a look if this solves your issue?

**Comment by hicolour** [comment]
@jcordes73 cool! My issue was basically that `Luxury Chocolate` test failed on some fragmented text, so if you mange to run it without failure I most probably owe you a :beer: 

I'll let you know tomorrow morning, if the tests are green on my side.

**Comment by hicolour** [comment]
works as a charm, thx a lot @jcordes73
@tfennelly is there any chance to release it officially, as it has major performance upgrade for groovy's cartridge users ?
