### ISSUE TITLE
How to map json to json

### ISSUE THREAD

**Issue by neoqing** [smooks/smooks#573]
Hi there,
I have a requirement likes , we have JSON file and its format is A, and we would like to use smooks to convert this JSON to another json file which its format is B, how can we achieve this ? I did find an example from https://github.com/smooks/smooks-examples. Would you please help with this? thanks.

**Comment by claudemamo** [comment]
You'd need to be more specific @neoqing. Have you gone through the [docs](https://www.smooks.org/v2/documentation/)? There is the [Smooks JSON reader](https://www.smooks.org/v2/documentation/#json) which ingests JSON and turns it into a stream of events. You could then map to the target JSON by using a [template language like FreeMarker](https://www.smooks.org/v2/documentation/#templating).

**Comment by neoqing** [comment]
thank you @claudemamo , your answer is very helpful, I'll try your suggested approach, just wondering if there could be a similar example. Thanks.

**Comment by claudemamo** [comment]
Currently no for JSON-to-JSON but I'll try to find some time to create one.
