### ISSUE TITLE
Upgrade to atleast java 9 to use Jakarta EE 9 namespace

### ISSUE THREAD

**Issue by hdip** [smooks/smooks#581]
Upgrading to atleast java 9 to use Jakarta EE 9 namespace will become increasingly necessary to play nice with other frameworks.
[Spring framework 6 and spring boot 3](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0) have this minimum requirement

Changes needed include references to  javax -> jakarta packages

**Comment by pwachira** [comment]
Maybe something like this https://github.com/pwachira/smooks/commit/3f965abe8218d1886b820ff66a94b5cac1464ec6

**Comment by timguy** [comment]
@pwachira this looks fine. Could you create a PR for your changes so all could benefit from it in an official release?

**Comment by claudemamo** [comment]
@hdip: I've been looking into this and, as I understand it, we don't need to compile to Java 9 so that Smooks can play nicely with other frameworks. Replacing references to the Javax Annotation API with the Jakarta Annotation API should be sufficient.
