### ISSUE TITLE
factory.toUNEdifact() BigDecimal Value...

### ISSUE THREAD

**Issue by cFl3iz** [smooks/smooks#601]
I am trying to build the [96a] version of Ordrsp and I am finding some problems so far.
My 'PRI' Segment looks like this: PRI+AAA:**3.6752**:CT::1.0:PCE'.
But when I use
[D96AInterchangeFactory.getInstance().toUNEdifact(myInterchange, ediOutStream);]
to build EDI..

Result Is PRI+AAA:**3.68**:CT::1.0:PCE

My Price value has fewer decimal places, it seems to be automatically rounded off.
and I don't know how to keep it the same, so I spent the night talking to 'gpt' but couldn't solve the problem.................

Ask everyone to help me.

**Comment by claudemamo** [comment]
Which version of Smooks are you running? Are you running the latest, 2.0.0-RC1?

**Comment by cFl3iz** [comment]
> 您运行的是哪个版本的 Smooks？您运行的是最新的 2.0.0-RC1 吗？
    pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-aggregator', version: '1.7.1.0', ext: 'pom'
    pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-binding', version: '1.7.1.0'
    pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-mapping', version: '1.7.1.0'

**Comment by cFl3iz** [comment]
> Which version of Smooks are you running? Are you running the latest, 2.0.0-RC1?
This is my current version of dependency
 pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-aggregator', version: '1.7.1.0', ext: 'pom'
    pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-binding', version: '1.7.1.0'
    pluginLibsCompile group: 'org.milyn.edi.unedifact', name: 'd96a-mapping', version: '1.7.1.0'
