### ISSUE TITLE
Fix artifact publishing to Nexus repo

### ISSUE THREAD

**Issue by tfennelly** [smooks/smooks#74]
Need to re-enable "deploy" profiles (lost during pom cleanup) so that we don't publish examples.  Also think we need to re-add the gpg plugin.  See RELEASE.md.

**Comment by manish-in-java** [comment]
Added a profile named `release` to enable releasing Maven artifacts to Maven Central. Release can be triggered by issuing the following command from the command line.

     mvn deploy -Prelease -Dgpg.keyname="[PGP signing key name]" -Dgpg.passphrase="[PGP signing key passphrase]"
