### ISSUE TITLE
Multi-thread issue within DataDecoder.Factory reported by Carsten Luxig

### ISSUE THREAD

**Issue by ieugen** [smooks/smooks#76]
Original message from Carsten Luxig:

Hi guys,

First of all we are happy to use Smooks. Thanks for your work.

I found an issue (v 1.4.1 and 1.5), that during initial loading of smooks under a high-load multi-threaded environment the DataDecoder.Factory is erroneous.

As outcome one can see an exception like

“ContentHandler class member 'org.milyn.javabean.ValueBinder#typeAlias' must define a decoder through it's @ConfigParam annotation.  Unable to automatically determine DataDecoder from member type.”

The root cause is, that one thread tries to load the decoders, while another thread tries to access them. Why this:

Before I start, the author of this class (probably tom.fennelly) should have a look, how Java synchronization is done and how to achieve it.
1.       private static volatile Map<Class, Class<? extends DataDecoder>> installedDecoders;
   volatile makes really no sense here, because this is used to share a reference over multiple threads and not to make the modification thread-safe. Well, a reference to a complex object is changed in two ways:

a.       specify a new instance, volatile has no effect

b.      set the instance to null, volatile has no effect

c.       volatile is used to synchronize the value of a field between all participating threads, immediately. Here static is used, hence installedDecoders is valid for all threads per definition. Usually volatile is not necessary, because it doesn’t locks the modification what is usually needed.
1. ```
     Even 100 null-checks wouldn’t bring thread-safeness. One cannot predict the point, where 1 thread is paused and another thread is waked up. See code:
   
   public static Class<? extends DataDecoder> getInstance(Class targetType) {
   
       if(installedDecoders == null) {
   
           loadInstalledDecoders();
   
       }
   
   
   
       if(targetType.isEnum()) {
   
           return EnumDecoder.class;
   
       } else {
   
           return installedDecoders.get(targetType);
   
       }
   
   }
   
   
   
   private synchronized static void loadInstalledDecoders() throws DataDecodeException {
   
       if(installedDecoders == null) {
   
           synchronized (Factory.class) {
   
               if(installedDecoders == null) {
   
                          installedDecoders = new HashMap<Class, Class<? extends DataDecoder>>();
   ```

The intension is clear, but it doesn’t help. Only one thread is able to step into “loadInstalledDecoders()” caused by the synchronized. The second synchronized locked over Factory.class is useless (and it shows the clueless about synchronization).
1.       The real problem:

a.       One thread A, the loading thread, reached the last line installedDecoders = new HashMap which changes immediately (due static and without static due volatile) the instance to be non-null and starts loading decoders.

b.      A second thread B steps meanwhile into getInstance(Class), now the check that installedDecoders == null is evaluated to false and the installedDecoders.get(Class) is returned. But unfortunately this might return null, because the first Thread A didn’t load a decoder for this Class right now.
1.       Solution:

a.       Remove useless volatile

b.      loadInstalledDecoders should be invoked without another null-check around, from getInstance

c.       loadInstalledDecoders is kept synchronized, keep also the first null-check their

d.      remove second synchronized over Factory.class, remove next null-check

e.      don’t create HashMap for reference installedDecoders, but create a temporary Map like Map loadedDecoders = new HashMap();

f.        after finishing the load-procedure publish the Map through changing reference installedDecoders = loadedDecoders;

g.       (The whole load-procedure must be performed, as already is, within loadInstalledDecoders)

I’d like to file this issue in your JIRA, but I don’t have the rights therefore.

Is it possible to fix this from beginning of version 1.4.1?

Thanks and kind regards

**Comment by timolson** [comment]
I also get this error, but we are single-threaded, everything running in main, although we use Groovy which may be doing something under the hood.
Perhaps it's a classloader ordering issue?  We tried using the Java classloader instead of the Groovy one, but without success.  Sometimes we do not see this error, but then we can take the same binary jar, put it on a different system, and it breaks.  Very strange - must be related to classloading or other platform-specific issues.
