### ISSUE TITLE
File encoding when reading EDI

### ISSUE THREAD

**Issue by janheise** [smooks/smooks#79]
Hi, I had/have problems with correct file encodings when reading EDI-Files that are different than the default encoding of the system. I looked around via Google but none of the fixes seemed to work for me. I dug into the sources and added the following fix.

For the implementation of the UNEdifactInterchangeFactory that I'm using, I added the following method:

```
public UNEdifactInterchange fromUNEdifact(Reader reader, InputStream stream, Result... additionalResults) throws IOException {
        StreamSource streamSource = new StreamSource();
        streamSource.setInputStream(stream);
        streamSource.setReader(reader);
```

So I could call it like:

```
InputStream fs = new FileInputStream(input);
BufferedReader br = new BufferedReader(new InputStreamReader(fs, "ISO-8859-1"));
UNEdifactInterchange interchange = factory.fromUNEdifact(br, fs);
```

The existing interface of UNEdifactInterchangeFactory seems not to be sufficient. I found no way to create an InputStream with the correct encoding and only supplying a correctly encoded InputSource was not sufficent. In the original Implementation there is:

```
public UNEdifactInterchange fromUNEdifact(InputSource ediSource, Result... additionalResults) throws IOException {
        StreamSource streamSource = new StreamSource();

        streamSource.setInputStream(ediSource.getByteStream());
        streamSource.setReader(ediSource.getCharacterStream());
```

According to the JavaDocs, StreamSource should only use the CharacterStream if one is supplied, but you have to use streamSource.setInputStream(), too. Otherwise smooks complains that it can not set the encoding that you set on the reader because it can not get the InputStream (Is this really necessary?). So I supplied both, a correctly encoded Reader (where I guess, smooks reads the encoding from) and the raw InputStream so that smooks can set the encoding.

I guess, calling ediSource.getByteStream() makes you lose the encoding within smooks due to some bug with InputSource?

I hope this all makes sense. If I oversaw the obvious, please enlighten me. 

Thank you for the time you put into smooks. Works like a charm otherwise!

Jan

**Comment by kattelus** [comment]
If I have correctly understood parser figures out encoding from UNB header automatically. Just make sure that original EDI file has correct info about encoding and just read from byte stream.

**Comment by claudemamo** [comment]
No longer applicable with the overhauled EDI cartridge in Smooks 2.
