### ISSUE TITLE
Provide example of Java to EDI

### ISSUE THREAD

**Issue by jacobemcken** [smooks/smooks#90]
I've been looking at Smooks for a while and have been toying with the EDI to Java transformation which works great.

I've tried to find an example for a transformation the other way around... could provide some pointers on how to do that or an actual example?

**Comment by gs11** [comment]
I'd be very interested in this too.

**Comment by jcordes73** [comment]
Maybe the example at http://stackoverflow.com/questions/12794416/smooks-edi-writer helps to get you started.

**Comment by gs11** [comment]
Thanks! Works just fine

**Comment by jcordes73** [comment]
@jacobemcken Are you happy to close it based on the example?

**Comment by jacobemcken** [comment]
Thanks for the example.
This isn't an issue for me anymore. I ended up writing my own parser in Clojure instead.
I'll close the issue... thanks for your time.
