### ISSUE TITLE
[OSGI] org.milyn.cdr.SmooksConfigurationException: Unable to locate Smooks digest configuration

### ISSUE THREAD

**Issue by rankec** [smooks/smooks#94]
Hi,
we decided to use Smooks in Apache Servicemix. We want to convert java -> edi. But we found a problem with the export packages. It was also mentioned some time ago here: http://milyn.996300.n3.nabble.com/Using-Smooks-1-5-1-in-an-OSGi-environment-td8671.html#a8677

The Solution was to add the META-INF.xsd.smooks to the Export-Package section in milyn-smooks-all-1.6.jar/META-INF/MANIFEST.MF. 

It would be nice, if you would fix this in the pom file. I just added one line and in the MANIFEST.MF the missing Export-Package appeared. :)

in smooks-all configuration my export-packages now look like this:

org.milyn._;-split-package:=merge-first;version="${project.version}",
                         META-INF.xsd.smooks,  <-- new line
                         META-INF.xsd.smooks._;-split-package:=merge-first,
                         !META-INF.services._,
                         !META-INF.maven._

Hope you understand what the problem is.

Best Regards

**Comment by alexproca** [comment]
I created PR #95 to update manifest. It will be available in the 1.7-SNAPSHOT branch. Maybe the commit should be ported as hotfix to 1.6  too.
