### ISSUE TITLE
FieldRef revisited

### ISSUE THREAD

**Issue by dhartford** [smooks/smooks#97]
Hi All,
Reading an old mailing thread around why there is SegRef, but not FieldRef from here:

http://milyn.996300.n3.nabble.com/Convert-UN-EDIFACT-td7727.html

The usecase I have is related specifically to the javabinding.  When using an X12 format such as 270/271, there are field types that are POINTER fields, where a different segment may have a field that is a pointer to a another segment's field (and usually points to a composite field).

The specific example is EQ DiagPointer field, pointing to an HI composite field, where there are several DiagPointers (with priority, so order matters) pointing to one of the 8 composite fields in HI...and all 8 composite fields are the same repeated composite fields in HI.

The workaround for this looks like when working from Java:

```
        ==================
        <Hi01,Hi02,Hi03,Hi04,Hi05,Hi06,Hi07,Hi08> find2100cHiByPointer(String diagPointer){
        ...
        //psudeocode
        when diagPointer = "02", return hl2100c.getHi.getHi02();
        //end psudeocode, and developer has 'to know' to cast to the right HI0X class
        ==================
```

FieldRef would be nice, as could have a single java class type 'HiCompField' that is reused for all 8 fields, rather than having each one be its own java class.

```
        <medi:segment segcode="HI">
        <!-- order matters, as setting priority of importance.  No such thing as 'fieldref' in smooks, desired to reuse same class -->

        <medi:field xmltag="HI01" fieldRef="HIFIELD:HICOMPFIELD" >...
        <medi:field xmltag="HI02" fieldRef="HIFIELD:HICOMPFIELD" >...
```

This is likely tied to the maven-ejc plugin that is very nicely generating the java bindings.

-D

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
