### ISSUE TITLE
What happened to segref?

### ISSUE THREAD

**Issue by mkleijwegt** [smooks/smooks#98]
I decided it was time to start using the import functionality when defining an edimap in order to reuse segments (as described here http://www.smooks.org/mediawiki/index.php?title=V1.5:Smooks_v1.5_User_Guide#Imports). However I cannot seem to get it to work with the 1.5 xsd (https://github.com/smooks/smooks/blob/master/edi/edisax/src/main/resources/META-INF/schema/edi-message-mapping-1.5.xsd). It complains that the segref is not allowed on a segment. Looking at the xsd this is indeed not allowed. In xsd 1.3 this was still available and in 1.4 it was gone.

Am I missing something? Is there another way of referencing a segment?

For now I have put a custom 1.5 xsd in my project and added the segref myself. This works.

Reason I need the 1.5 version is because you can specify ignoreUnmappedFields="true" on a segment which is very handy as well.

Hope you can help.

Best regards,
Mark

**Comment by dxxr** [comment]
The attribute was renamed to `nodeTypeRef`

**Comment by mkleijwegt** [comment]
Ah I see. Would be good to amend this in the documentation to make it more clear.
Thanks for your help!

**Comment by claudemamo** [comment]
The issue is no longer applicable: the next Smooks release replaces MEDI with DFDL.
